### ISSUE TITLE
acme-unified not installing at NERSC

### ISSUE THREAD

**Issue by xylar** [UV-CDAT/conda-recipes#13]
I'm having trouble installing the latest acme-unified package on NERSC (both Edison and Cori).  I'm seeing the following error:
```
ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'defaults::gcc-4.8.5-7'.
LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.13/bin/.gcc-post-link.sh
==> script messages <==
<None>


Attempting to roll back.



LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information
location of failed script: /project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.13/bin/.gcc-post-link.sh
==> script messages <==
<None>
```

My procedure was:
* Made a new miniconda2 environment with `Miniconda2-latest-Linux-x86_64.sh` (I don't seem to be able to use the `python/2.7-anaconda` to create a new environment because I don't have permission to download new packages)
* manually (and temporarily) added the bin directory from this new installation to my `$PATH`
* Created a new anaconda environment specifically for acme-unified:
```bash
conda create -p /project/projectdirs/acme/software/anaconda_envs/cori_acme_unified_2017.9.13 python=2
```
* activate the new environment:
```bash
source activate /project/projectdirs/acme/software/anaconda_envs/cori_acme_unified_2017.9.13
```
* Install acme-unified (without x11):
```bash
conda install -c conda-forge -c uvcdat -c acme acme-unified mesalib
```
(This is where I see the error above)

**Comment by xylar** [comment]
@doutriaux1, any help you could provide would be very much appreciated.  I also tried only installing `uvcdat and mesalib` (see below) and I get the same error:
```
> conda install -c conda-forge -c uvcdat -c acme uvcdat mesalib
```

**Comment by xylar** [comment]
For now, I'm going to try manually installing the packages (with pinned versions) needed by MPAS-Analysis to make sure we're okay on that side at least.

**Comment by xylar** [comment]
I think the problem was something to do with disk quota, though I'm still a bit baffled.  Anyway, I *think* I'm getting a working install now.  I'll re-open if I have further problems.

**Comment by doutriaux1** [comment]
@xylar glad I could help 😜
